version: '3.7'

services:

  sample:
    image: ${UI_IMAGE_NAME?}:${UI_IMAGE_TAG?}
    restart: ${RESTART_POLICY?}
    container_name: ${UI_CONTAINER_NAME?}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${UI_IMAGE_NAME?}:${UI_IMAGE_TAG?}
        - ${UI_IMAGE_NAME?}:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true