version: '3.7'

services:

  fast-food-ui:
    image: ${UI_IMAGE_NAME?}:${UI_IMAGE_TAG?}
    restart: ${RESTART_POLICY?}
    container_name: ${UI_CONTAINER_NAME?}
    build:
      context: ./src/contoso-ui
      dockerfile: Dockerfile
      tags:
        - ${UI_IMAGE_NAME?}:${UI_IMAGE_TAG?}
        - ${UI_IMAGE_NAME?}:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000

  test:
    image: ${UI_IMAGE_NAME?}-test:${UI_IMAGE_TAG?}
    build:
      context: ./src/contoso-ui
    environment:
      - CI=true
    command: npm test