version: '3.7'

services:

  contoso-ui:
    image: ${UI_IMAGE_NAME?}:${UI_IMAGE_TAG?}
    restart: ${RESTART_POLICY?}
    container_name: ${UI_CONTAINER_NAME?}
    build:
      context: ./src/contoso-ui
      dockerfile: Dockerfile
      tags:
        - ${UI_IMAGE_NAME?}:${UI_IMAGE_TAG?}
        - ${UI_IMAGE_NAME?}:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${UI_PORT?}:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  test:
    build:
      context: ./src/contoso-ui
    environment:
      - CI=true
    command: npm test